export const LOAD_FLIGHTS_REQUEST = 'LOAD_FLIGHTS_REQUEST'
export const LOAD_FLIGHTS_SUCCESS = 'LOAD_FLIGHTS_SUCCESS'
export const LOAD_FLIGHTS_FAIL = 'LOAD_FLIGHTS_FAIL'

export const LOAD_FLIGHT_REQUEST = 'LOAD_FLIGHT_REQUEST'
export const LOAD_FLIGHT_SUCCESS = 'LOAD_FLIGHT_SUCCESS'
export const LOAD_FLIGHT_FAIL = 'LOAD_FLIGHT_FAIL'

export const SAVE_SEATS_DISPATCH = 'SAVE_SEATS_DISPATCH'
export const SAVE_SEATS_SUCCESS = 'SAVE_SEATS_SUCCESS'
export const SAVE_SEATS_FAIL = 'SAVE_SEATS_DISPATCH'

export const FLIGHT_UPDATE_DISPATCH = 'FLIGHT_UPDATE_DISPATCH'
export const FLIGHT_UPDATE_SUCCESS = 'FLIGHT_UPDATE_SUCCESS'
export const FLIGHT_UPDATE_FAIL = 'FLIGHT_UPDATE_DISPATCH'
export const FLIGHT_UPDATE_RESET = 'FLIGHT_UPDATE_RESET'

export const FLIGHT_DELETE_DISPATCH = 'FLIGHT_DELETE_DISPATCH'
export const FLIGHT_DELETE_SUCCESS = 'FLIGHT_DELETE_SUCCESS'
export const FLIGHT_DELETE_FAIL = 'FLIGHT_DELETE_DISPATCH'
export const FLIGHT_DELETE_RESET = 'FLIGHT_DELETE_RESET'

export const FLIGHT_ADD_DISPATCH = 'FLIGHT_ADD_DISPATCH'
export const FLIGHT_ADD_SUCCESS = 'FLIGHT_ADD_SUCCESS'
export const FLIGHT_ADD_FAIL = 'FLIGHT_ADD_DISPATCH'
export const FLIGHT_ADD_RESET = 'FLIGHT_ADD_RESET'