export const SAVE_BILLING_DISPATCH = 'SAVE_BILLING_DISPATCH';
export const SAVE_BILLING_SUCCESS = 'SAVE_BILLING_SUCCESS';
export const SAVE_BILLING_FAIL = 'SAVE_BILLING_FAIL';

export const SAVE_PAYMENT_DISPATCH = 'SAVE_PAYMENT_DISPATCH'
export const SAVE_PAYMENT_SUCCESS = 'SAVE_PAYMENT_SUCCESS'
export const SAVE_PAYMENT_FAIL = 'SAVE_PAYMENT_FAIL'

export const ORDER_CREATE_DISPATCH = 'ORDER_CREATE_DISPATCH'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_FETCH_DISPATCH = 'ORDER_FETCH_DISPATCH'
export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS'
export const ORDER_FETCH_FAIL = 'ORDER_FETCH_FAIL'
export const ORDER_FETCH_RESET = 'ORDER_FETCH_RESET'

export const ORDER_PAID_DISPATCH = 'ORDER_PAID_DISPATCH'
export const ORDER_PAID_SUCCESS = 'ORDER_PAID_SUCCESS'
export const ORDER_PAID_FAIL = 'ORDER_PAID_FAIL'
export const ORDER_PAID_RESET = 'ORDER_PAID_RESET'

export const ORDER_USER_DISPATCH = 'ORDER_USER_DISPATCH'
export const ORDER_USER_SUCCESS = 'ORDER_USER_SUCCESS'
export const ORDER_USER_FAIL = 'ORDER_USER_FAIL'

export const GET_ORDERS_DISPATCH = 'GET_ORDERS_DISPATCH'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL'