export const USER_CREATE_DISPATCH = 'USER_CREATE_DISPATCH'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL'

export const USER_LOGIN_DISPATCH = 'USER_LOGIN_DISPATCH'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET'

export const USER_PROFILE_DISPATCH = 'USER_PROFILE_DISPATCH'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const USER_UPDATE_DISPATCH = 'USER_UPDATE_DISPATCH'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USERS_GET_DISPATCH = 'USERS_GET_DISPATCH'
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS'
export const USERS_GET_FAIL = 'USERS_GET_FAIL'

export const USER_DELETE_DISPATCH = 'USER_DELETE_DISPATCH'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_RESET = 'USER_DELETE_RESET'

export const USER_ADMIN_DISPATCH = 'USER_ADMIN_DISPATCH'
export const USER_ADMIN_SUCCESS = 'USER_ADMIN_SUCCESS'
export const USER_ADMIN_FAIL = 'USER_ADMIN_FAIL'

export const UPDATE_USER_DISPATCH = 'UPDATE_USER_DISPATCH'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'